### ISSUE TITLE
Uninitialized constant Refinery::Blog unless I've already installed refinerycms (edge) on the system

### ISSUE THREAD

**Issue by j-h-l** [refinery/refinerycms-blog#426]
I was trying to deploy my refinerycms-edge and blog to vps and noticed that it would stop at migration (rake db:migrate and rake db:setup):
```
rake aborted!                                                                                                                 
NameError: uninitialized constant Refinery::Blog
/var/www/k/tmp/build-142735232018048/config/initializers/refinery/blog.rb:1:in `<top (required)>'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:648:in `block in load_config_initializer'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/notifications.rb:161:in `instrument'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:647:in `load_config_initializer'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:611:in `each'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:611:in `block in <class:Engine>'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `run'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:44:in `each'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/www/k/tmp/build-142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/k/tmp/build142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/application.rb:300:in `initialize!'
/var/www/k/tmp/build-142735232018048/config/environment.rb:5:in `<top (required)>'
/var/www/k/tmp/build142735232018048/vendor/bundle/ruby/2.2.0/gems/railties-4.1.8/lib/rails/application.rb:276:in `require_environment!'
```

Before running on different directory on same system:
```
rails new app_name -m http://refinerycms.com/t/edge
```
I would get uninitialized constant error message, but after, it seems to run fine.
Am I missing something here?  Some 'require' somewhere?
Thank you

**Comment by anitagraham** [comment]
It sounds as though you have the initializer but not the gem. Is it in your gemfile?

**Comment by j-h-l** [comment]
My Gemfile
```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'
# Use sqlite3 as the database for Active Record
group :development, :test do
  gem 'sqlite3'
end
# Use SCSS for stylesheets
gem 'bootstrap-sass'
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]


gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'master'

gem 'quiet_assets', :group => :development

# Add support for searching inside Refinery's admin interface.
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']

# Add support for Refinery's custom fork of the visual editor WYMeditor.
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']

gem 'refinerycms-blog', git: 'https://github.com/refinery/refinerycms-blog', branch: 'master'

gem 'angularjs-rails', '~> 1.3.10'
gem 'ngmin-rails'

gem 'haml'

gem 'lodash-rails'
gem 'autoprefixer-rails'

gem 'mina'

gem 'pg'
```

and Gemfile.lock
```
GIT
  remote: https://github.com/refinery/refinerycms
  revision: 139c6b99f344619603209f5a4b979b67aabf07ad
  branch: master
  specs:
    refinerycms (3.0.0)
      refinerycms-authentication (= 3.0.0)
      refinerycms-core (= 3.0.0)
      refinerycms-images (= 3.0.0)
      refinerycms-pages (= 3.0.0)
      refinerycms-resources (= 3.0.0)
    refinerycms-authentication (3.0.0)
      actionmailer (>= 4.0.2, < 5.0)
      devise (~> 3.0, >= 3.2.4)
      friendly_id (~> 5.1.0)
      refinerycms-core (= 3.0.0)
    refinerycms-core (3.0.0)
      actionpack (>= 4.1.5, < 5.0)
      activerecord (>= 4.1.5, < 5.0)
      awesome_nested_set (~> 3.0.0)
      coffee-rails (~> 4.0, >= 4.0.0)
      decorators (~> 2.0.0)
      jquery-rails (>= 2.3.0)
      jquery-ui-rails (~> 5.0.0)
      railties (>= 4.1.5, < 5.0)
      refinerycms-i18n (~> 3.0.0)
      sass-rails (>= 4.0, < 5.1)
      truncate_html (~> 0.9)
      will_paginate (~> 3.0.2)
    refinerycms-images (3.0.0)
      dragonfly (~> 1.0.0)
      refinerycms-core (= 3.0.0)
    refinerycms-pages (3.0.0)
      awesome_nested_set (~> 3.0.0)
      babosa (!= 0.3.6)
      friendly_id (~> 5.1.0)
      globalize (>= 4.0.0, < 5.2)
      refinerycms-core (= 3.0.0)
      seo_meta (~> 2.0.0.rc.1)
    refinerycms-resources (3.0.0)
      acts_as_indexed (~> 0.8.0)
      dragonfly (~> 1.0.0)
      refinerycms-core (= 3.0.0)

GIT
  remote: https://github.com/refinery/refinerycms-blog
  revision: 6495058a6e524f02d955bddd1dce7afa83fb97f6
  branch: master
  specs:
    refinerycms-blog (3.0.0)
      acts-as-taggable-on
      filters_spam (~> 0.2)
      friendly_id (~> 5.1.0)
      globalize (>= 4.0.0, < 5.2)
      jquery-ui-rails (~> 5.0.0)
      rails_autolink (~> 1.1.3)
      refinerycms-core (~> 3.0.0)
      refinerycms-settings (~> 3.0.0)
      refinerycms-wymeditor (~> 1.0.1)
      seo_meta (~> 2.0.0.rc.1)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.1.8)
      actionpack (= 4.1.8)
      actionview (= 4.1.8)
      mail (~> 2.5, >= 2.5.4)
    actionpack (4.1.8)
      actionview (= 4.1.8)
      activesupport (= 4.1.8)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    actionview (4.1.8)
      activesupport (= 4.1.8)
      builder (~> 3.1)
      erubis (~> 2.7.0)
    activemodel (4.1.8)
      activesupport (= 4.1.8)
      builder (~> 3.1)
    activerecord (4.1.8)
      activemodel (= 4.1.8)
      activesupport (= 4.1.8)
      arel (~> 5.0.0)
    activesupport (4.1.8)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    acts-as-taggable-on (3.5.0)
      activerecord (>= 3.2, < 5)
    acts_as_indexed (0.8.3)
    addressable (2.3.7)
    angularjs-rails (1.3.14)
    arel (5.0.1.20140414130214)
    autoprefixer-rails (5.1.7.1)
      execjs
      json
    awesome_nested_set (3.0.2)
      activerecord (>= 4.0.0, < 5)
    babosa (1.0.2)
    bcrypt (3.1.10)
    bootstrap-sass (3.3.4.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.2.19)
    builder (3.2.2)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.3.0)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1)
    decorators (2.0.0)
      railties (>= 4.0.0, < 5.0.0)
    devise (3.4.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    dragonfly (1.0.7)
      addressable (~> 2.3)
      multi_json (~> 1.0)
      rack
    erubis (2.7.0)
    execjs (2.4.0)
    filters_spam (0.5)
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    globalize (4.0.3)
      activemodel (>= 4.0.0, < 5)
      activerecord (>= 4.0.0, < 5)
    haml (4.0.6)
      tilt
    hike (1.2.3)
    i18n (0.7.0)
    jbuilder (2.2.12)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (3.1.2)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.3)
      railties (>= 3.2.16)
    json (1.8.2)
    lodash-rails (3.5.0)
      railties (>= 3.1)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.4.3)
    mina (0.3.3)
      open4 (~> 1.3.4)
      rake
    minitest (5.5.1)
    multi_json (1.11.0)
    ngmin-rails (0.4.0)
      rails (>= 3.1)
    open4 (1.3.4)
    orm_adapter (0.5.0)
    pg (0.18.1)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.5.2)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.1.8)
      actionmailer (= 4.1.8)
      actionpack (= 4.1.8)
      actionview (= 4.1.8)
      activemodel (= 4.1.8)
      activerecord (= 4.1.8)
      activesupport (= 4.1.8)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.8)
      sprockets-rails (~> 2.0)
    rails-i18n (4.0.4)
      i18n (~> 0.6)
      railties (~> 4.0)
    rails_autolink (1.1.6)
      rails (> 3.1)
    railties (4.1.8)
      actionpack (= 4.1.8)
      activesupport (= 4.1.8)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
    refinerycms-acts-as-indexed (2.0.1)
      acts_as_indexed (~> 0.8.0)
      decorators (~> 2.0.0)
      refinerycms-core (~> 3.0.0)
    refinerycms-i18n (3.0.1)
      rails-i18n (~> 4.0.1)
      routing-filter (>= 0.4.0)
    refinerycms-settings (3.0.0)
      friendly_id (~> 5.0, >= 5.0.1)
      refinerycms-core (~> 3.0, >= 3.0.0)
    refinerycms-wymeditor (1.0.6)
      refinerycms-core (~> 3.0, >= 3.0.0)
    responders (1.1.2)
      railties (>= 3.2, < 4.2)
    routing-filter (0.4.0.1)
      actionpack (< 4.2)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    seo_meta (2.0.0.rc.1)
      railties (>= 3.0.0)
    spring (1.3.3)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.2.4)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sqlite3 (1.3.10)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    truncate_html (0.9.3)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    warden (1.2.3)
      rack (>= 1.0)
    will_paginate (3.0.7)

PLATFORMS
  ruby

DEPENDENCIES
  angularjs-rails (~> 1.3.10)
  autoprefixer-rails
  bootstrap-sass
  coffee-rails (~> 4.0.0)
  haml
  jbuilder (~> 2.0)
  jquery-rails
  lodash-rails
  mina
  ngmin-rails
  pg
  quiet_assets
  rails (= 4.1.8)
  refinerycms!
  refinerycms-acts-as-indexed (~> 2.0, >= 2.0.0)
  refinerycms-blog!
  refinerycms-wymeditor (~> 1.0, >= 1.0.6)
  sass-rails (~> 4.0.3)
  sdoc (~> 0.4.0)
  spring
  sqlite3
  uglifier (>= 1.3.0)
```

**Comment by anitagraham** [comment]
Definitely there. 

However that is the exact error one gets if you comment out the gem, but leave the initializer. 

Do you need to run a bundle install on the deployed system?

**Comment by bricesanchez** [comment]
No news since more than 8 months, i close the issue. Thank you all !

**Comment by vinchi777** [comment]
add this in you application.rb
`
require 'refinerycms'
`

**Comment by ljrzarate** [comment]
Still getting this error, any help?
